apiVersion: v1
kind: Service
metadata:
  name: main-api
spec:
  selector:
    app: main-api
  ports:
    - protocol: TCP
      port: 3000 # port the service exposes
      targetPort: 3000 # port the container listens on
  type: ClusterIP # internal access only
